from os import getenv

KINDLE_EMAIL = getenv('KINDLE_EMAIL')
AMAZON_EMAIL = getenv('AMAZON_EMAIL')

EMAIL_PASSWORD = getenv('EMAIL_PASSWORD')
SMTP_HOST_NAME = getenv('SMTP_HOST_NAME')

# DEFAULT SMTP PORT IS 587 for non SSL in GMail, SET YOURS HERE TO CHANGE

SMTP_PORT = getenv('SMTP_PORT', 587)
MERCURY_API_KEY = getenv('MERCURY_API_KEY')


